[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "paramperceptnet"
version = "0.0.1"
requires-python = ">=3.10, <3.14"
dependencies = [
  "jax; sys_platform != 'linux'",
  "jax[cuda12]; sys_platform == 'linux'",
  "jaxlib",
  "flax",
  "optax",
  "clu",
  "ml_collections",
  "fxlayers @ git+https://github.com/Jorgvt/fxlayers.git",
  "safetensors>=0.7.0",
  "iqadatasets @ git+https://github.com/Jorgvt/iqadatasets.git",
  "JaxPlayground @ git+https://github.com/Jorgvt/JaxPlayground.git",
  "wandb",
  "einops",
  "orbax-checkpoint>=0.3.0,<0.5",
  "numpy>=2.2.6",
]

[project.optional-dependencies]
examples = [
  "Pillow",
  "requests",
  "huggingface_hub",
  "datasets",
  "matplotlib",
  "safetensors",
  "tensorstore<0.1.67"
]

[tool.uv]
environments = ["sys_platform != 'win32'"]

[tool.setuptools]
packages = ["paramperceptnet"]

[tool.uv.sources]
iqadatasets = { git = "https://github.com/Jorgvt/iqadatasets.git" }

[dependency-groups]
test = [
    "iqadatasets",
    "piq>=0.8.0",
    "tqdm>=4.67.3",
]
